---
- hosts: vmlab
  user: student
  become: yes
  vars:
    seneca_id: ssharma608
  tasks:
    - name: Install/Update Apache
      yum:
        name: httpd
        state: latest

    - name: Install EPEL
      yum:
        name: epel-release
        state: present

    - name: Remove tree
      yum:
        name: tree
        state: absent

    - name: Set hostname
      hostname:
        name: "{{ seneca_id }}"

    - name: Create new user
      user:
        name: "{{ seneca_id }}"
        groups: wheel
        append: yes
        shell: /bin/bash

    - name: Copy SSH key
      authorized_key:
        user: "{{ seneca_id }}"
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

    - name: Create lab directories
      file:
        path: "/home/{{ seneca_id }}/ops445/lab{{ item }}"
        state: directory
        owner: "{{ seneca_id }}"
        group: "{{ seneca_id }}"
        mode: '0755'
      loop: "{{ range(1,9)|list }}"

